import { useState, type ReactNode } from "react"
import {
  Copy,
  RefreshCw,
  ThumbsUp,
  ThumbsDown,
  Check,
  Download,
  ExternalLink,
  FileText,
} from "lucide-react"
import { AgentActivity } from "./AgentActivity"
import { MessageAttachment } from "./FileAttachment"
import { useToast } from "../ui/Toast"
import { backendUrl } from "../../services/backendConfig"
import type { Message, AgentStep } from "../../types"

interface ChatMessageProps {
  message: Message
  onLike?: () => void
  onDislike?: () => void
  onRegenerate?: () => void
  onUpdateMessage?: (updates: Partial<Message>) => void
  streaming?: boolean
  streamContent?: string
  /** Live steps from SSE while streaming (shown instead of message.agentSteps) */
  liveSteps?: AgentStep[]
}

export function ChatMessage({
  message,
  onLike,
  onDislike,
  onRegenerate,
  streaming,
  streamContent,
  liveSteps,
}: ChatMessageProps) {
  const [copied, setCopied] = useState(false)
  const { showToast } = useToast()

  const content = streaming ? streamContent || "" : message.content

  async function handleCopy() {
    await navigator.clipboard.writeText(content)
    setCopied(true)
    showToast("Copied to clipboard")
    setTimeout(() => setCopied(false), 2000)
  }

  function handleDownloadReport(name: string) {
    const blob = new Blob(
      [
        `NIMBUS ZERO WORKBENCH\nGenerated Report: ${name}\n\nThis is a demo report generated by Nimbus Zero Engine.\n\nDocument classification: CONFIDENTIAL\nProcessed on-premise. No external transmission.`,
      ],
      { type: "text/plain" },
    )
    const url = URL.createObjectURL(blob)
    const a = document.createElement("a")
    a.href = url
    a.download = name.replace(".pdf", ".txt")
    a.click()
    URL.revokeObjectURL(url)
    showToast("Report downloaded")
  }

  if (message.role === "user") {
    return (
      <div className="flex justify-end mb-6 animate-fade-in">
        <div className="max-w-[75%] flex flex-col gap-2 items-end">
          {message.attachments?.map((att) => (
            <MessageAttachment key={att.id} attachment={att} />
          ))}
          {message.content && (
            <div
              className="px-4 py-3 rounded-2xl rounded-br-md text-sm text-[var(--text-primary)] leading-relaxed"
              style={{
                background: "rgba(124,92,255,0.18)",
                border: "1px solid rgba(124,92,255,0.25)",
              }}
            >
              {message.content}
            </div>
          )}
          <div className="text-[10px] text-[var(--text-muted)]">
            {new Date(message.timestamp).toLocaleTimeString([], {
              hour: "2-digit",
              minute: "2-digit",
            })}
          </div>
        </div>
      </div>
    )
  }

  return (
    <div className="flex gap-3 mb-6 animate-fade-in">
      <div className="flex-shrink-0 w-7 h-7 rounded-lg bg-[var(--accent)] flex items-center justify-center mt-1">
        <svg width="13" height="13" viewBox="0 0 14 14" fill="none">
          <path
            d="M7 1L9.5 5.5H12L8.5 8.5L9.5 13L7 10.5L4.5 13L5.5 8.5L2 5.5H4.5L7 1Z"
            fill="white"
            fillRule="evenodd"
          />
        </svg>
      </div>
      <div className="flex-1 min-w-0">
        <div className="flex items-center gap-2 mb-2">
          <span className="text-xs font-semibold text-[var(--text-primary)]">
            Nimbus Zero
          </span>
          <span className="text-[10px] text-[var(--text-muted)]">
            {new Date(message.timestamp).toLocaleTimeString([], {
              hour: "2-digit",
              minute: "2-digit",
            })}
          </span>
        </div>

        {/* Agent Activity — ABOVE the content, matching Claude/ChatGPT layout */}
        {(() => {
          const stepsToShow =
            streaming && liveSteps && liveSteps.length > 0
              ? liveSteps
              : message.agentSteps
          return stepsToShow && stepsToShow.length > 0 ? (
            <AgentActivity steps={stepsToShow} streaming={streaming} />
          ) : null
        })()}

        {/* Response content — shown below the activity panel */}
        {(content || !streaming) && (
          <div className="prose-ai text-sm text-[var(--text-secondary)] leading-relaxed mt-2">
            <FormattedContent content={content} />
            {streaming && (
              <span className="inline-block w-0.5 h-4 bg-[var(--accent)] cursor-blink ml-0.5 align-middle" />
            )}
          </div>
        )}

        {/* While streaming and no content yet: subtle "working" placeholder */}
        {streaming && !content && (
          <div className="mt-2 flex items-center gap-1.5 text-[11px] text-[var(--text-muted)]">
            <span className="inline-block w-0.5 h-4 bg-[var(--accent)]/60 animate-pulse" />
          </div>
        )}

        {/* Generated Files */}
        {message.generatedFiles && message.generatedFiles.length > 0 && (
          <div className="mt-3 flex flex-col gap-2">
            {message.generatedFiles.map((f) => (
              <div
                key={f.id}
                className="flex items-center gap-3 px-3 py-2.5 rounded-lg bg-[var(--bg-card)] border border-[var(--accent)]/20 max-w-[360px] shadow-sm"
              >
                <div className="flex-shrink-0 w-8 h-8 rounded-lg bg-[var(--accent)]/10 border border-[var(--accent)]/20 flex items-center justify-center">
                  <FileText size={14} className="text-[var(--accent)]" />
                </div>
                <div className="flex-1 min-w-0">
                  <div className="text-xs font-medium text-[var(--text-primary)] truncate">
                    {f.name}
                  </div>
                  <div className="text-[10px] text-[var(--text-muted)] uppercase tracking-wide">
                    {f.type} · {f.size}
                  </div>
                </div>
                <div className="flex gap-1">
                  {f.download_url ? (
                    <a
                      href={backendUrl(f.download_url)}
                      download={f.name}
                      target="_blank"
                      rel="noreferrer"
                      className="px-2 py-1 text-[10px] rounded bg-[var(--accent)]/10 border border-[var(--accent)]/30 text-[var(--accent)] hover:bg-[var(--accent)]/20 transition-colors flex items-center gap-1"
                    >
                      <Download size={9} /> Download
                    </a>
                  ) : (
                    <button
                      onClick={() => handleDownloadReport(f.name)}
                      className="px-2 py-1 text-[10px] rounded bg-[var(--accent)]/10 border border-[var(--accent)]/30 text-[var(--accent)] hover:bg-[var(--accent)]/20 transition-colors flex items-center gap-1"
                    >
                      <Download size={9} /> Download
                    </button>
                  )}
                </div>
              </div>
            ))}
          </div>
        )}

        {/* Actions */}
        {!streaming && (
          <div className="flex items-center gap-1 mt-3">
            <button
              onClick={handleCopy}
              className="flex items-center gap-1 px-2 py-1 rounded text-[11px] text-[var(--text-muted)] hover:text-[var(--text-primary)] hover:bg-white/5 transition-colors"
            >
              {copied ? (
                <Check size={11} className="text-[var(--success)]" />
              ) : (
                <Copy size={11} />
              )}
              {copied ? "Copied!" : "Copy"}
            </button>
            <button
              onClick={onRegenerate}
              className="flex items-center gap-1 px-2 py-1 rounded text-[11px] text-[var(--text-muted)] hover:text-[var(--text-primary)] hover:bg-white/5 transition-colors"
            >
              <RefreshCw size={11} /> Regenerate
            </button>
            <button
              onClick={onLike}
              className={`flex items-center gap-1 px-2 py-1 rounded text-[11px] transition-colors ${
                message.liked
                  ? "text-[var(--success)] bg-[var(--success)]/10"
                  : "text-[var(--text-muted)] hover:text-[var(--text-primary)] hover:bg-white/5"
              }`}
            >
              <ThumbsUp size={11} />
            </button>
            <button
              onClick={onDislike}
              className={`flex items-center gap-1 px-2 py-1 rounded text-[11px] transition-colors ${
                message.disliked
                  ? "text-[var(--danger)] bg-[var(--danger)]/10"
                  : "text-[var(--text-muted)] hover:text-[var(--text-primary)] hover:bg-white/5"
              }`}
            >
              <ThumbsDown size={11} />
            </button>
          </div>
        )}
      </div>
    </div>
  )
}

function FormattedContent({ content }: { content: string }) {
  // Simple markdown-ish renderer
  const lines = content.split("\n")
  const elements: ReactNode[] = []
  let i = 0

  while (i < lines.length) {
    const line = lines[i]

    if (line.startsWith("## ")) {
      elements.push(<h2 key={i}>{line.slice(3)}</h2>)
    } else if (line.startsWith("# ")) {
      elements.push(<h1 key={i}>{line.slice(2)}</h1>)
    } else if (line.startsWith("- ") || line.startsWith("• ")) {
      const listItems: string[] = []
      while (
        i < lines.length &&
        (lines[i].startsWith("- ") || lines[i].startsWith("• "))
      ) {
        listItems.push(lines[i].slice(2))
        i++
      }
      elements.push(
        <ul key={`list-${i}`}>
          {listItems.map((item, j) => (
            <li
              key={j}
              dangerouslySetInnerHTML={{ __html: formatInline(item) }}
            />
          ))}
        </ul>,
      )
      continue
    } else if (line.trim() === "") {
      // skip blank lines between paragraphs
    } else {
      elements.push(
        <p key={i} dangerouslySetInnerHTML={{ __html: formatInline(line) }} />,
      )
    }
    i++
  }

  return <>{elements}</>
}

function formatInline(text: string): string {
  return text
    .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
    .replace(/`(.+?)`/g, "<code>$1</code>")
}
